In [1]:
import pandas as pd
import numpy as np
import sklearn.metrics as metrics
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
dataset= pd.read_csv('Social_Network_Ads (1).csv')

In [3]:
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [4]:
# now we split the dataset  into yhrt dependent and the independent variable
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [6]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [8]:
#now we will split the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3)
print(X_train)

[[    46  82000]
 [    22  18000]
 [    27  58000]
 [    27  20000]
 [    29  75000]
 [    36  50000]
 [    35  97000]
 [    26  32000]
 [    45 131000]
 [    24  23000]
 [    30  89000]
 [    27  96000]
 [    38  61000]
 [    47  47000]
 [    34  43000]
 [    49 141000]
 [    32 100000]
 [    47 113000]
 [    45  32000]
 [    49  74000]
 [    40  71000]
 [    46  28000]
 [    48 141000]
 [    50  44000]
 [    30 107000]
 [    38  55000]
 [    40 107000]
 [    39 106000]
 [    46 117000]
 [    44 139000]
 [    39  79000]
 [    39  42000]
 [    41  63000]
 [    48 138000]
 [    39 122000]
 [    42  54000]
 [    23  20000]
 [    32 117000]
 [    58 101000]
 [    36  54000]
 [    40  57000]
 [    29  83000]
 [    40  57000]
 [    27  57000]
 [    35  25000]
 [    35 108000]
 [    54  26000]
 [    49  28000]
 [    47 105000]
 [    35  61000]
 [    31 118000]
 [    21  72000]
 [    30  62000]
 [    28  32000]
 [    38  71000]
 [    34 115000]
 [    26  16000]
 [    19  76000]
 [    48  2900

In [9]:
# now feature scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)


[[ 0.84414971  0.31724663]
 [-1.49180683 -1.47347174]
 [-1.00514922 -0.35427276]
 [-1.00514922 -1.41751179]
 [-0.81048618  0.12138681]
 [-0.12916552 -0.57811255]
 [-0.22649704  0.73694624]
 [-1.10248074 -1.08175209]
 [ 0.74681819  1.68826537]
 [-1.29714379 -1.33357186]
 [-0.71315465  0.51310645]
 [-1.00514922  0.70896627]
 [ 0.06549753 -0.27033284]
 [ 0.94148123 -0.66205248]
 [-0.32382856 -0.77397238]
 [ 1.13614428  1.96806512]
 [-0.51849161  0.82088617]
 [ 0.94148123  1.18462583]
 [ 0.74681819 -1.08175209]
 [ 1.13614428  0.09340683]
 [ 0.26016057  0.00946691]
 [ 0.84414971 -1.19367199]
 [ 1.03881276  1.96806512]
 [ 1.2334758  -0.7459924 ]
 [-0.71315465  1.01674599]
 [ 0.06549753 -0.43821268]
 [ 0.26016057  1.01674599]
 [ 0.16282905  0.98876601]
 [ 0.84414971  1.29654573]
 [ 0.64948666  1.91210517]
 [ 0.16282905  0.2333067 ]
 [ 0.16282905 -0.80195235]
 [ 0.3574921  -0.21437289]
 [ 1.03881276  1.8841252 ]
 [ 0.16282905  1.4364456 ]
 [ 0.45482362 -0.46619266]
 [-1.39447531 -1.41751179]
 

In [1]:
# now we will train the model using logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)



NameError: name 'X_train' is not defined