In [ ]:
import pandas as pd
import numpy as np

import seaborn as sns

In [3]:
dataset= pd.read_csv('Cars.csv')

In [4]:
dataset.head(5)

buying  maint doors persons lug_boot safety    car
0  vhigh  vhigh   two     two    small    low  unacc
1  vhigh  vhigh   two     two    small    med  unacc
2  vhigh  vhigh   two     two    small   high  unacc
3  vhigh  vhigh   two     two      med    low  unacc
4  vhigh  vhigh   two     two      med    med  unacc

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Split features and target
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

# One-hot encode categorical features in X
X = pd.get_dummies(X)

# Encode target if it's categorical
le = LabelEncoder()
y = le.fit_transform(y)

# Scale features
sc = StandardScaler()
X = sc.fit_transform(X)


In [10]:
## now we divide the dataset into training and testing sets
from sklearn.model_selection import train_test_split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Import the necessary libraries for the model


In [12]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Split the data (assuming X and y are already defined and processed)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.2f}")


Confusion Matrix:
[[ 44   4  34   0]
 [  2   1   6   0]
 [  4   0 238   0]
 [  7   3   3   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.54      0.63        82
           1       0.12      0.11      0.12         9
           2       0.85      0.98      0.91       242
           3       0.00      0.00      0.00        13

    accuracy                           0.82       346
   macro avg       0.44      0.41      0.42       346
weighted avg       0.78      0.82      0.79       346


Accuracy: 0.82


c:\Users\Ali Jawad\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ali Jawad\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ali Jawad\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf