In [54]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [55]:
df= pd.read_csv('D:\c desktop data\Python\Ann\Churn_Modelling.csv')

In [56]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [57]:
# now we asign the value of x and the value of y
x = df.iloc[:,3:13].values
# why i start from 3 and not 0
# because the first three columns are not features
# and the last column is not a feature
# the last column is the dependent variable
y = df.iloc[:, 13].values

In [58]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [59]:
print(y)

[1 0 1 ... 1 1 0]


In [60]:
# now we have the datset in whiich some feature that are catgorical so we convert into the numberic
from sklearn.preprocessing import LabelEncoder
# we use the LabelEncoder to convert the categorical data into numeric data
le = LabelEncoder()   # that are the object
# we convert the categorical data into numeric data
le.fit(df['Gender'])
df['Gender'] = le.transform(df['Gender'])


In [61]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France       0   42   
1             2    15647311       Hill          608     Spain       0   41   
2             3    15619304       Onio          502    France       0   42   
3             4    15701354       Boni          699    France       0   39   
4             5    15737888   Mitchell          850     Spain       0   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France       1   39   
9996       9997    15569892  Johnstone          516    France       1   35   
9997       9998    15584532        Liu          709    France       0   36   
9998       9999    15682355  Sabbatini          772   Germany       1   42   
9999      10000    15628319     Walker          792    France       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [62]:
# now thw geography featuree have more than binary catory so we use the one hot encoding
# we use the get_dummies to convert the categorical data into numeric data
# give me the onehot encoder libary ad import
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# we use the ColumnTransformer to convert the categorical data into numeric data

ct = ColumnTransformer([('encoder', OneHotEncoder(drop='first'), [1])], remainder='passthrough')
# 1 are we defined the columns
x = ct.fit_transform(x)

In [63]:
print(x)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [64]:
### now we diivde the testing and thetraiining data
from sklearn.model_selection import train_test_split
# we use the train_test_split to split the data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [65]:
print(X_train.dtypes)
print(X_train.head())

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [66]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd

# Assuming X_train and X_test are your datasets (pandas DataFrames)
# Identify categorical columns (e.g., 'Geography', 'Gender')
categorical_cols = ['Geography', 'Gender']  # Adjust based on your dataset
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Create ColumnTransformer to encode categorical columns
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(drop='first', sparse_output=False), categorical_cols)
    ],
    remainder='passthrough'  # Keep numerical columns unchanged
)

# Create a pipeline to combine encoding and scaling
pipeline = Pipeline([
    ('encoder', ct),  # Apply one-hot encoding
    ('scaler', StandardScaler())  # Apply scaling to all columns
])

# Apply transformations to training and test data
X_train_scaled = pipeline.fit_transform(X_train)
X_test_scaled = pipeline.transform(X_test)

AttributeError: 'numpy.ndarray' object has no attribute 'select_dtypes'

In [ ]:
## now we do the feature standard scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

ValueError: could not convert string to float: 'Female'

In [ ]:
pip install keras

  Using cached rich-14.0.0-py3-none-any.whl.metadata (18 kB)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 3.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
   ------------------------ --------------- 1.8/3.0 MB 9.1 MB/s eta 0:00:01
   ------------------------------- -------- 2.4/3.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  2.9/3.0 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 3.0/3.0 MB 4.0 MB/s eta 0:00:00
Using cached rich-14.0.0-py3-none-any.whl (243 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.wh


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
## we make the input layer and the first hidden layer
hidden_layer = tf.keras.layers.Dense(units=6, activation='relu', )
hidden_layer1 = tf.keras.layers.Dense(units=6, activation='relu')

In [ ]:
%pip install tensorflow


from keras.layers import Dense, Dropout, Activation, Flatten,sequential



Note: you may need to restart the kernel to use updated packages.Collecting tensorflow
  Using cached protobuf-5.29.4-cp310-abi3-win_amd64.whl.metadata (592 bytes)
   ---------------------------------------- 0.0/375.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/375.7 MB ? eta -:--:--
   ---------------------------------------- 1.0/375.7 MB 3.0 MB/s eta 0:02:07
   ---------------------------------------- 1.8/375.7 MB 3.1 MB/s eta 0:01:59
   ---------------------------------------- 2.4/375.7 MB 3.1 MB/s eta 0:02:00
   ---------------------------------------- 3.1/375.7 MB 3.1 MB/s eta 0:02:02
   ---------------------------------------- 3.7/375.7 MB 3.1 MB/s eta 0:02:02
   ---------------------------------------- 4.5/375.7 MB 3.1 MB/s eta 0:02:01
    --------------------------------------- 5.0/375.7 MB 3.1 MB/s eta 0:02:00
    --------------------------------------- 5.8/375.7 MB 3.1 MB/s eta 0:01:58
    --------------------------------------- 6.6/375.7 MB 3.2 MB/s eta 


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
## we make the input layer and the first hidden layer
import tensorflow as tf

hidden_layer = tf.keras.layers.Dense(units=6, activation='relu', )
hidden_layer1 = tf.keras.layers.Dense(units=6, activation='relu')
# we make the output layer
output_layer = tf.keras.layers.Dense(units=1 , activation='sigmoid',kernel_initializer='uniform')
tf.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



AttributeError: module 'tensorflow' has no attribute 'compile'

In [67]:
tf.fit(X_train_scaled, y_train, epochs=10, batch_size=32)

AttributeError: module 'tensorflow' has no attribute 'fit'

In [1]:
# %% [markdown]
# Import libraries
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# %% [markdown]
# Load dataset
df = pd.read_csv('D:\c desktop data\Python\Ann\Churn_Modelling.csv')

# %% [markdown]
# Display dataset
df

# %% [markdown]
# Select features (x) and target (y)
# Start from column 3 to exclude RowNumber, CustomerId, Surname
x = df.iloc[:, 3:13]
y = df.iloc[:, 13].values  # Target variable (Exited)

# %% [markdown]
# Encode categorical variables: 'Gender' and 'Geography'
# Label encode 'Gender' (binary: Male/Female)
le = LabelEncoder()
x['Gender'] = le.fit_transform(x['Gender'])

# One-hot encode 'Geography' (multiple categories)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(drop='first', sparse_output=False), ['Geography'])],
    remainder='passthrough'
)
x = ct.fit_transform(x)

# %% [markdown]
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# %% [markdown]
# Check data types and sample
print(pd.DataFrame(X_train).dtypes)
print(pd.DataFrame(X_train).head())

# %% [markdown]
# Apply feature scaling
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

# %% [markdown]
# Build the ANN model
model = Sequential([
    Dense(units=6, activation='relu', input_shape=(X_train_scaled.shape[1],)),  # Input + first hidden layer
    Dense(units=6, activation='relu'),  # Second hidden layer
    Dense(units=1, activation='sigmoid')  # Output layer
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# %% [markdown]
# Train the model
model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_data=(X_test_scaled, y_test))

# %% [markdown]
# Evaluate the model
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
dtype: object
    0    1      2    3     4    5          6    7    8    9          10
0  0.0  1.0  667.0  0.0  34.0  5.0       0.00  2.0  1.0  0.0  163830.64
1  1.0  0.0  427.0  1.0  42.0  1.0   75681.52  1.0  1.0  1.0   57098.00
2  0.0  0.0  535.0  0.0  29.0  2.0  112367.34  1.0  1.0  0.0  185630.76
3  0.0  1.0  654.0  1.0  40.0  5.0  105683.63  1.0  1.0  0.0  173617.09
4  0.0  1.0  850.0  0.0  57.0  8.0  126776.30  2.0  1.0  1.0  132298.49


c:\Users\Ali Jawad\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.7975 - loss: 0.5295 - val_accuracy: 0.7975 - val_loss: 0.4787
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7952 - loss: 0.4676 - val_accuracy: 0.7975 - val_loss: 0.4501
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7984 - loss: 0.4433 - val_accuracy: 0.7975 - val_loss: 0.4381
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7977 - loss: 0.4322 - val_accuracy: 0.7975 - val_loss: 0.4335
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7956 - loss: 0.4278 - val_accuracy: 0.7975 - val_loss: 0.4301
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7950 - loss: 0.4361 - val_accuracy: 0.7975 - val_loss: 0.4274
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7917 - loss: 0.4342 - val_accuracy: 0.8085 - val_loss: 0.4260
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8080 - loss: 0.4285 - val_accu